name: pelmeni-ya-zabil-vkl-actions

services:
  frontend:
    image: ${DOCKER_USER:-krosy}/docker-project-frontend:latest
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - bridge
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "256M"

  backend:
    image: ${DOCKER_USER:-krosy}/docker-project-backend:latest
    restart: unless-stopped
    expose:
      - "8081"
    networks:
      - bridge
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "256M"

networks:
  bridge:
    driver: bridge
